### ISSUE TITLE
Mod compatibility

### ISSUE THREAD

**Issue by sorviel** [UnearthedArcana/Scales_of_Balance#13]
Hey

The reforged ability bonuses (eg, CHA giving XP bonus) won't work with some kitted CHARNAMES, that use kits from mods.

Example : 
CHARNAME is a nightblade (mage/thief kit from Shadow Magic mod) : SOB bonuses apply
CHARNAME is a warlock : SOB bonuses won't apply.

(both kits are from mods by the same author).

Also, with Shadow Magic, for some reason, the bonus spells from high stats won't apply by SOB but by Shadow Magic.

(also, for other reasons and not wanting to pollute threads, I'd like to contact you - subtledoctor - for some project. Any contact preference?)

**Comment by subtledoctor** [comment]
Intended. Aionz's mods that give stat bonuses to their own kits will continue to use their own stat bonuses; all other kits will use the SoB bonuses.
