### ISSUE TITLE
Incorrect Kit Styles

### ISSUE THREAD

**Issue by JoePagano** [UnearthedArcana/Scales_of_Balance#18]
Noticed this while editing SnS availability in 124_WPO_styles.tpa:

![image](https://user-images.githubusercontent.com/7797551/135668202-8ba8184b-90e0-468c-97b8-26de5beec025.png)

Should be d5_wizards_array and d5_mc_mages_array, right?

**Comment by subtledoctor** [comment]
fixed, thanks
