### ISSUE TITLE
Creature dying when spawning - Negative Stat Issue

### ISSUE THREAD

**Issue by kingzork** [UnearthedArcana/Scales_of_Balance#22]
The Phoenix Guard enemy(PHEOGURD.CRE) spawns already dead in the game, investigating the creature file using EEkeeper, i noticed that the creature Dexterity Stat is really low( 3 points), with the changes made to armor in the armor revision component of the mod, and the fact that the creature uses plate mail armor( -5 minus Dex ), is possible that the resulting negative dexterity of -2 is causing the phoenix guard to spawn already dead. I changed the creature file to have a higher Dex stat (12) and the phoenix guard spawned normally. Please fix this issue, has it could be affecting other types of enemies with low Dexterity.

**Comment by subtledoctor** [comment]
fixed
