### ISSUE TITLE
Proficiencies and EEUITweaks: Display max proficiency limits

### ISSUE THREAD

**Issue by Hettikus** [UnearthedArcana/Scales_of_Balance#23]
While you cant get more than 3 pips in a proficiency with, for example, an assassin in 2da its still max 4 which make EEUITweaks component show incorrect maximum  for specific proficiency.

**Comment by subtledoctor** [comment]
That mod doesn’t generally work well with mods that change the proficiency system (e.g. this, or Kjeron’s Dual-to-kit mod)
