### ISSUE TITLE
5.6.3 Component 200 (for EE 1.4+) installation bug

### ISSUE THREAD

**Issue by EmeraldAngel** [UnearthedArcana/Scales_of_Balance#4]
[SETUP-SCALES_OF_BALANCE.zip](https://github.com/UnearthedArcana/Scales_of_Balance/files/873990/SETUP-SCALES_OF_BALANCE.zip)

I uploaded my debug file as I could not find your contact information.

**Comment by subtledoctor** [comment]
Fixed, thanks for the report!
