### ISSUE TITLE
Descriptions in Character Creation

### ISSUE THREAD

**Issue by Alicyl** [UnearthedArcana/Scales_of_Balance#7]
After installing Scales of Balance, I noticed that the descriptions for the Races have been **completely** changed, and the descriptions for the Classes have been altered as well—Fighter and Ranger having blank descriptions, and... Druids being called "Soft Feet".

Is there a component or file within your mod I can uninstall or remove to reverse the descriptions? I never wanted nor asked for them to be changed.

**Comment by Alicyl** [comment]
There is also a problem with the descriptions for Skills as shown below:

![Baldur_6YNG4M8GSU](https://user-images.githubusercontent.com/13776859/71575847-14394980-2ab4-11ea-970b-42f281b44e31.png)

**Comment by subtledoctor** [comment]
You need to use DLC Merger before installing mods on SoD
