### ISSUE TITLE
Repository seems broken for windows users

### ISSUE THREAD

**Issue by Lixiss** [UnearthedArcana/Scales_of_Balance#8]
I noticed what no more can checkout this repository on windows, because 5.18 commit introduced file with invalid name.

So checkout ends with error:
```
error: invalid path 'Mac_Weidu_Launcher_v7.app/Icon?'
```

**Comment by Lixiss** [comment]
Well, for self i'm was able to workaround this via rewriting history by completely removing unrelated folder:

Run command over local repository:
```
git filter-branch --tree-filter "rm -rf Mac_Weidu_Launcher_v7.app" -- origin/master
```

**Comment by Lixiss** [comment]
```
git checkout --force origin/master
```
probably way to go.

```
>git status
HEAD detached at origin/master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    "Mac_Weidu_Launcher_v7.app/Icon\r"
```

As you see, Icon file name has CR char at the end...

**Comment by subtledoctor** [comment]
Sorry, I'm not very proficient with Git... I don't even know what "checkout" it.  The repo is designed such that players who want to use the mod should get the .zip archive from the Releases, and anyone who wants to muck around with the mod can fork it and, of on Windows, just delete the Mac files?  (I'm on a Mac and I don't actually see the file path you reference.)

**Comment by ALIENQuake** [comment]
@Lixiss This issue is now fixed!
@subtledoctor You can close this issue now \o/

**Comment by Lixiss** [comment]
Issue seems fixed now. Thanks.
